<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3in_profilepic"
 *
 * Auto generated by Extension Builder 2020-10-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'FEuser Profile pic',
    'description' => 'set feuser profile pic with crop  tool',
    'category' => 'plugin',
    'author' => 'Vikram Mandal',
    'author_email' => 'vikrammandal@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
